[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/customers"
  to = "/customers.html"
  status = 200

[[redirects]]
  from = "/customer/add"
  to = "/customers.html"
  status = 200

[[redirects]]
  from = "/customer/:id/edit"
  to = "/customers.html"
  status = 200

[[redirects]]
  from = "/customer/:id/projects"
  to = "/projects.html?customerId=:id"
  status = 200

[[redirects]]
  from = "/sales-reps"
  to = "/sales-reps.html"
  status = 200

[[redirects]]
  from = "/visits"
  to = "/visits.html"
  status = 200

[[redirects]]
  from = "/projects"
  to = "/projects.html"
  status = 200

[[redirects]]
  from = "/project/add"
  to = "/projects.html"
  status = 200

[[redirects]]
  from = "/project/:id/edit"
  to = "/projects.html"
  status = 200

[[redirects]]
  from = "/projects/:projectId/tasks"
  to = "/tasks.html?projectId=:projectId"
  status = 200

[[redirects]]
  from = "/projects/:projectId/users"
  to = "/projects.html"
  status = 200

[[redirects]]
  from = "/project/:projectId/tasks"
  to = "/tasks.html?projectId=:projectId"
  status = 200

[[redirects]]
  from = "/tasks"
  to = "/tasks.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/task-labels"
  to = "/task-labels.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
